# 公共配置文件
spring:
  application:
    name: aigc
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # 分布式 session
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigc
    username: root
    password:
  # Redis 配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password:

  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 50MB
      max-request-size: 50MB

#todo 修改ip
server:
#  address: 202.146.220.165
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        same-site: none
        secure: true
  tomcat:
    max-swallow-size: 50MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

# 对象存储
cos:
  client:
    accessKey: AKID7EE93yiGg4JSQCan2999qS0OWXVN7ct6
    secretKey: CD250jGbmjYSIxdliUAkJfOzVpukZDgw
    region: ap-beijing
    bucket: original-1317028174

